name: Build Artifact

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Artifact
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build Solution
      run: |
        MSBuild.exe SagaScript.csproj  -property:Configuration=Debug
        ls -al
  
  