name: Build Artifact

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Artifact
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build Project
      run: |
        MSBuild.exe SagaScript.csproj  -property:Configuration=Release
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: SagaScript
        path: '${{ github.workspace }}/bin/Release/SagaScript.dll'

    - name: Upload Artifact Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ github.workspace }}/bin/Release/SagaScript.dll
  